### ISSUE TITLE
Reusable (retained) PVs with iSCSI

### ISSUE THREAD

**Issue by oliverblaha** [democratic-csi/democratic-csi#141]
Background:
- I have a helm-installed application that needs persistent storage.
- I would like to store its data in a PV that is retained if the pod and its PVC are deleted.
- When re-installing the pod, it should bind to the same PV again.
- CSI functions (incl. snapshots) must be available (for the backup system I'm planning to use).

Current Situation: dynamic provisioning works; node-manual works, too.

Unfortunately, the node-manual driver seems to not support any snapshots.

- Is it even possible to use zfs-generic-iscsi for manual PVs?
- Alternatively, is it possible to use dynamic provisioning, but have new instances connect to the same PV again?

I don't mind setting up the volume myself, although it would be nice if the provisioner did it for me.
However, snapshots need to be managed automatically.

Appreciate any hints!

**Comment by travisghansen** [comment]
Welcome! Sorry I missed this when you created it.

So this problem domain is really (IMO) outside the realm of csi and/or this driver unfortunately. There are probably some workflows that would work however.

- deploy with storage class reclaim policy as `Retain`
- create a pv via a pvc as normal
- delete pvc (pv will remain due to reclaim policy)
- create a new pvc but specifically bind it to the pv created in step 2 (https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reserving-a-persistentvolume)

The doc says the not set a storage class but I think you’ll need to set it for ongoing operations (ie: snapshots, etc) to function.

Give it a try and let me know!

**Comment by theautomation** [comment]
Remove the claimRef in the PV with ```kubectl patch pv <pv name> -p '{"spec":{"claimRef": null}}'``` then set the PV volumeName in the PVC this will bound the existing PV to the new PVC.

**Comment by TheAceMan** [comment]
I am attempting the same, see comments here https://github.com/democratic-csi/democratic-csi/issues/273

The previous comment clears out the entire claimRef, only clearing the uid of the claimref will make the PV available for a PVC with the given name (assuming you are recreating it with the same name.) Then you can just create the PVC as normal and it will use the existing PV with the claimRef but no uid value.

**Comment by croneter** [comment]
Thanks @TheAceMan, this worked wonderfully! :heart:
