### ISSUE TITLE
 Failed to pull image  toomanyrequests

### ISSUE THREAD

**Issue by davisglenn** [democratic-csi/democratic-csi#185]
Hi,
I am getting an error message:
 **Failed to pull image "docker.io/democraticcsi/democratic-csi:latest": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests**
I know this is common if you do not have a login.  But I don't see a place where I can login to dockerhub.  
I'm also not sure why its even asking for a new version when I already have the latest on my server.  But I guess because the helm chart always requests the latest, its probably always tries.  
Is there any way to just have it use a specific version so it doesn't always check for the latest?
Is there parameters to set so I can login with my dockerhub credentials?
thanks for any help and let me know if you need any other information.

**Comment by travisghansen** [comment]
Welcome!

You can pin the version:

- https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/valueshould%20fail%20when%20no%20volume%20capability%20is%20provideds.yaml#L163
- https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L221

I don't think the chart has image pull secret support yet unfortunately. Generally I see that handled at a 'lower level' anyhow but it would be nice to add to the chart.

For example, if your nodes run docker it's common to point the daemon at a registry mirror (the same can be used for containerd and others). The mirror would be setup with docker hub user account. Then you are getting multiple benefits:

- cutting down on requests by orders of magnitude due to using a proxy that all nodes point to
- increasing the number of requests available to you generally by setting the proxy with docker hub creds

As an aside, I actually do have images being pushed to ghcr as well, but I think that requires credentials anyway so again without support in the chart that doesn't help much either :(

**Comment by davisglenn** [comment]
Thank you so much for the quick response!!  
Funny because I tried to put the image option: 
image:
  pullPolicy: Never
But it didn't work because I think I put it in the wrong place.
BTW - the first link did not work, but the 2nd one should explain it.
I will give it a try!!
Thanks again!!

**Comment by travisghansen** [comment]
Fixed the link.

**Comment by davisglenn** [comment]
Thanks for your help!  That works great!
