### ISSUE TITLE
Questions on zfs-local-dataset driver with Nomad

### ISSUE THREAD

**Issue by nahsi** [democratic-csi/democratic-csi#197]
1. Is it possible to supply ZFS properties for dataset when creating a volume? I see it can be done with zfs-ephemeral driver (using volume_context and property.<name>) but have not found I way to do that with zfs-local-dataset
2. How can I specify on which host dataset should be created? It seems that now volume is created on the Nomad client that receives the call to create a volume. 

Deletion also doesn't seem to work when request to delete lands on node that doesn't have a dataset. What I mean is that if I have nodes `node-01` and `node-02`, when I create a volume with `NOMAD_ADDR=node-01:4646 nomad volume create test.hcl` dataset will be created at `node-01` and when I run `NOMAD_ADDR=node-02:4646 nomad volume delete test` volume will be deleted from Nomad but dataset will stay at `node-01`.

**Comment by travisghansen** [comment]
You can set properties statically here: https://github.com/democratic-csi/democratic-csi/blob/master/examples/zfs-local-dataset.yaml#L7

If it’s possible to alter the parameters of the create volume call you can also use this syntax here: https://github.com/democratic-csi/democratic-csi/blob/master/examples/freenas-api-nfs.yaml#L33 which would allow you to dynamically set it on a per-volume basis.

Specifying which host is tricky business and generally not the concern of the driver but rather the ‘CO’ (container orchestrator) in csi spec. K8S has very specific setup of the csi bits that I’m not sure Nomad yet supports.

Perhaps @scaleoutsean or @tgross can shed some light on the matter?

**Comment by nahsi** [comment]
@travisghansen The trick with templating worked! Thank you.

Is there a way to set a default value? For example:
```yaml
  datasetProperties:
    recordsize: "{{ parameters.recordsize }}"
    quota: "{{ parameters.quota }}"
```
But if I omit `quota` in volume parameters I will get:
```
Error creating volume: Unexpected response code: 500 (rpc error: 1 error occurred:
        * controller create volume: CSI.ControllerCreateVolume: controller plugin returned an internal error, check the plugin allocation logs for more information: rpc error: code = Internal desc = Error: cannot create 'main/nomad/dataset/v/test': bad numeric value ''
 Error: cannot create 'main/nomad/dataset/v/test': bad numeric value ''

    at Object.zfsError (/home/csi/app/src/utils/zfs.js:78:16)
    at /home/csi/app/src/utils/zfs.js:949:42
    at ChildProcess.<anonymous> (/home/csi/app/src/utils/zfs.js:1595:11)
    at ChildProcess.emit (node:events:538:35)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Comment by travisghansen** [comment]
Those are https://handlebarsjs.com/ templates so you may be able to do something like this:

```
{{#if someval}}{{ someval }}{{else}}{{"default"}}{{/if}}
```

The code should probably detect empty values generally and ignore them but that could end up hiding issues that operators would like to see.

**Comment by nahsi** [comment]
If I'm not mistaken specifying host where to create a dataset should be done with [`topology_request`](https://www.nomadproject.io/docs/commands/volume/create#topology_request-parameters)?

For example if I'm using aws-ebs-csi and want to create a volume in `ap-northeast-1a` availability zone i will use 
```hcl
topology_request {
  required {
    topology {
      segments {
        "topology.ebs.csi.aws.com/zone" = "ap-northeast-1a"
      }
    }
  }
}
```

In case of democratic-csi this should work
```hcl
topology_request {
  required {
    topology {
      segments {
        "org.democratic-csi.topology/node" = "palmyra"
      }
    }
  }
}
```

But it doesn't work since `org.democratic-csi.topology/node` is overwritten ([probably?](https://github.com/democratic-csi/democratic-csi/blob/master/README.md?plain=1#L157)) somewhere ([here?](https://github.com/democratic-csi/democratic-csi/blob/ae9791d5009ab36ab5131c9f83a32b4853974c14/src/driver/controller-local-hostpath/index.js#L82)).

If it is overwritten perhaps there should be some logic like if `org.democratic-csi.topology/node` is set then do not overwrite it?


Nomad job for reference:
```hcl
riables {
  versions = {
    csi = "1.6.3"
  }
}

job "democratic-csi" {
  datacenters = ["syria"]
  namespace   = "infra"
  type        = "system"

  group "monolith" {
    task "monolith" {
      driver = "docker"

      env {
        CSI_NODE_ID = node.unique.name
      }

      config {
        image    = "democraticcsi/democratic-csi:v${var.versions.csi}"
        hostname = node.unique.name

        privileged = true
        ipc_mode   = "host"
        network_mode = "host"

        args = [
          "--log-level=info",
          "--driver-config-file=${NOMAD_TASK_DIR}/config.yml",
          "--csi-name=org.democratic-csi.zfs-local-dataset",
          "--csi-version=1.5.0",
          "--csi-mode=controller",
          "--csi-mode=node",
          "--server-socket=/csi/csi.sock",
        ]

        mount {
          type     = "bind"
          target   = "/host"
          source   = "/"
          readonly = true
        }
      }

      csi_plugin {
        id        = "zfs-local-dataset"
        type      = "monolith"
        mount_dir = "/csi"
      }

      template {
        data        = file("zfs-local-dataset.yml")
        destination = "${NOMAD_TASK_DIR}/config.yml"
        left_delimiter = "[["
        right_delimiter = "]]"
      }

      resources {
        cpu    = 30
        memory = 50
      }
    }
  }
}
```

**Comment by travisghansen** [comment]
Topology comes into play but in a slightly different way in these scenarios. There are some core concepts to understand before going into detail:

1. in the csi spec there are 2 key implementers, `SP` (storage provider, ie: csi driver/democratic-csi) and `CO` (container orchestrator, ie: k8s, Nomad, etc)
2. On the `SP` side of the equation there are 2 groups of services: `Node` and `Controller`

In a non-distributed setup (ie: storage not local to the node) typically the `Node` and `Controller` services run as separate process. `Node` runs on all cluster nodes and `Controller` runs...somewhere, generally in the cluster and generally only 1 instance for the whole deployment/cluster. The `CreateVolume` request goes to the `Controller` service.

In a distributed setup each node runs both the `Node` and `Controller` services.

The trouble with sending the `topology_request` in this context is the decision should have already been made about which node the volume should be scheduled/created on implicitly by nature of the fact that the instance of the `Controller` service receiving the request should be the same node the workload is desired to be run on. There are effectively 2 variations of this however:

1. Operator (you) tells the `CO` where the workload should run and the `CO` should invoke the `CreateVolume` request on the appropriate node
2. `CO` picks *any* node to run the `CreateVolume` request and the driver responds with topology that limits the workload to be scheduled only on that node when it is ready to run

The k8s mechanism to control this behavior is found here: https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode

In any case, whenever/wherever the volume is created `democratic-csi` will automatically **return** to the `CO` the relevant topology information (`"org.democratic-csi.topology/node" = "<nodeid>"`) so that the `CO` knows in the future which node(s) can handle the workload and only schedule as appropriate. In addition, for this particular style of deployment (distributed/node local) the `CO` should ensure that all future `Controller` methods are only invoked on the node(s) with the appropriate topology constraints. This is the detail behind my previous comment about delete invocations triggered on the appropriate node is actually a `CO` concern.

Indeed the driver is hard-coded to return the topology constraint 'pinning' the volume to the relevant node in the `CreateVolume` request. Any explicitly requested topology constraints in the `CreateVolume` request are ignored (I should probably check them and make sure that if sent for whatever reason that I reject the request if they do not match the constraints of the executing node).

- https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/controller-zfs/index.js#L1189
- https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/controller-zfs/index.js#L1203
- https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/controller-zfs-local/index.js#L205
- https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/controller-zfs-local/index.js#L221

**Comment by nahsi** [comment]
Thank you for very detailed anwser! I understand. I will experiment with democratic-csi on Nomad, based on what I've learned from you, and will share the result here. And perhaps will update the docs later if all is nice.
