### ISSUE TITLE
Multiple Controllers

### ISSUE THREAD

**Issue by jklaw90** [democratic-csi/democratic-csi#206]
First off thank you for making this project it's awesome!

My question was regarding how many controllers i should be expecting to run. 
It looks like i'd be running a controller per nfs/iscsi based on the helm chart.
In addition to that am i correct in thinking if i have two different pools (ssd vs hdd) id want to run a controller per each even if i wanted to use iscsi on both?

And a slightly off topic question, is there a way to mount an existing nfs dataset created from the truenas gui?

**Comment by travisghansen** [comment]
You’re thinking is correct, controller-per-config essentially. So if using iscsi with 2 different parent datasets (ie: pools) you would deploy once for each.

`node-manual` driver allows you to connect to existing shares (of any kind that the driver supports, so nfs, iscsi, smb, etc). You only need one deployment of the `node-manual` driver to handle any/all of the supported filesystems etc. See the examples to get an idea how this works.

**Comment by jklaw90** [comment]
thank you for the help! also curious why rewrote your controller from go to nodejs?
I'm definitely not as familiar nodejs but if there is any features needed around truenas scale happy to help.

**Comment by travisghansen** [comment]
I didn't start the original nfs provisioner and it was written in go so I just went along for the ride. Moving to a grpc based model (csi) make a much cleaner separation and I'm more familiar with node than go (and there are least some perceived rigid aspects of go in this context that I didn't want...for example I wanted to allow runtime selection of csi version/proto files, perhaps go supports this but my perception was that with all the autogenerated grpc code it wouldn't end well for what I wanted).

Thanks for the offer to help! I'm actually touching up a few things currently to work with SCALE 22.12 right now but otherwise I think the feature set is covered.
