### ISSUE TITLE
Is it possible to allow dynamic PV creation for a static NFS share?

### ISSUE THREAD

**Issue by tobz** [democratic-csi/democratic-csi#223]
Hey there!

I've been trying to suss this out from the documentation but I have to admit my brain is a bit mushy after doing so (not your fault, just trying to mentally juggle all of the relevant parts) and figured it might be simplest to just ask:

__Is it possible to create a storage class for dynamic PV/PVC provisioning that can use an existing NFS export/share?__

My goal essentially boils down to wanting to do what `node-manual` seems to be more or less designed for, but entirely with a statically-configured `StorageClass` such that I can simply create `PersistentVolumeClaim` resources and get the normal dynamic provisioning of PVs on-the-fly. I have a few fixed NFS exports (shared media, general data, yadda yadda) that I want to expose uniformly to various containers, and for my own (perhaps over-the-top) desire for concise, I'd love to avoid having to bake the PV manually for each of those locations. It just feels weird to have to do that.

**Comment by travisghansen** [comment]
Welcome! It can definitely be a sea of information to digest when delving into the world of k8s so don’t despair!

So I’m not entirely sure what you’re after but there are 2 things that seem relevant:

- `node-manual` allows you to connect to pre-created shares and this project will not manage the life-cycle of the shares (meaning it won’t delete them if you delete the PV/PVC etc)
- `nfs-client` which effectively uses a single share and creates sub-dirs per-pvc for you (and deletes them as well)

The latter is what you want if you want to experience roughly the ‘k8s way’ of how the storage ux is intended. I say roughly because the various `nfs-client` style projects out there all do essentially the same thing…create a dir per pv ‘under’ an existing share. This approach lacks quota enforcement (per pv) and is quite crude speaking generally, however it’s great because it works with storage systems that may not otherwise have sane/deeper integration with k8s/csi.

What storage system are you leveraging?

**Comment by tobz** [comment]
I'm on FreeNAS, but I guess I just explained poorly.

I basically want to get the benefits of a dynamic provisioner -- single PVC, all relevant configuration baked into a storage class, that can trigger the PV creation -- but without actually trying to allocate storage... literally just map the PV to a specific NFS share a la `node-manual`.

**Comment by travisghansen** [comment]
Is there something about `node-manual` that does not fully fit the use-case?

If I'm understanding correctly you want a storage class that *always* spits out the same PV with a PVC is created?

**Comment by tobz** [comment]
That's correct.

It's mostly just a question around whether or not I could conceivably avoid having to define the PV a priori for every place I want to use a particular known NFS share.

**Comment by travisghansen** [comment]
OK, it doesn't really make sense to include something of that nature in this project (it is arguably very niche). However, leveraging the `node-manual` features you couple fairly easily create your own 'operator' (effectively storage class) to achieve this goal.

The idea is the operator would watch select PVCs and create PVs that adhere to the `node-manual` syntax in an automated fashion.

https://github.com/flant/shell-operator

A little shell mixed with `kubectl` (in the shell script) would likely be pretty quick.

**Comment by tobz** [comment]
Yeah, fair enough.

I mostly just wasn't sure if there was an existing way to push the CSI configuration, when using the `node-manual` driver, from the PV itself to a storage class that could be used dynamically.

Appreciate the response/rubber ducking. 👍🏻
