### ISSUE TITLE
Question on Disk Space Reclaim

### ISSUE THREAD

**Issue by reefland** [democratic-csi/democratic-csi#229]
My storage plan has been to use `democratic-csi` for large datasets (like Prometheus databases, etc)  and use Longhorn storage for smaller ones.

I've learned that Longhorn does not have the ability to reclaim disk space (does not support TRIM/UNMAP operations, so the discard mount option or fstrim in the filesystem layer cannot reclaim the unused blocks https://github.com/longhorn/longhorn/issues/836) and is thus not appropriate for use with any delete heavy workloads.

Not knowing this I allocated 5Mi volume to hold a 400KB file that got updated frequently.... it has over provisioned to 32Mi and will keep growing. Prometheus Alert: `The actual space used by Longhorn volume pvc-a343686e-a0c9-4d0d-9766-554ec9b00828 on k3s02 is at 358.3984375% capacity.`

In re-working my storage strategy, I have to ask... does `democratic-csi` have any space reclaim limitations on either iSCSI or NFS?

Thanks.

**Comment by travisghansen** [comment]
Some notes from the TrueNAS team..

```
Our iSCSI does support UNMAP in all fashions as soon as LUN is backed by ZVOLs.  FreeBSD had no support for hole-punching in files up to 14, so TrueNAS Core still can not do it for regular files either via iSCSI or NFS.  That is why we recommend ZVOLs for iSCSI. (edited) 

Likewise for SCALE. ZFS does support discard operations on zvols but not on filesystems. So I expect for democratic-csi that UNMAP over iSCSI would be supported, but FITRIM over NFS would not. What actually happens to the underlying storage is a lot more complicated of course. Things like compression and snapshots can dramatically change what you think you're doing to a file.

You can allocate a 5M file and with compression it will only take up however much the 400K compresses to

And then if you have a snapshot and change or even delete the file it can still take up that space, so hopefully Prometheus has some smarts to it in that regard
```

In short, IMO TRIM is only relevant for zvols and trim+zvol+iscsi should be in good shape.

For very odd scenarios where you try to trim raw image files over nfs (or smb, or whatever file-based sharing system) then perhaps you may run into limitations.

Frankly space usage/requirements for zfs are generally pretty tricky due to a myriad of considerations including compression, snapshots, thin provisioning, etc. In general and IMO zfs does what it should and what you expect it to do.

As an aside, I'm quite shocked longhorn has this problem given the use-cases for longhorn (k8s and harvester). Crazy...I've already subscribed to the linked issue so I can follow along with the progress.
