### ISSUE TITLE
TrueNAS CORE -> SCALE migration

### ISSUE THREAD

**Issue by djjudas21** [democratic-csi/democratic-csi#262]
I'm asking as I couldn't find an explicit answer in the docs. I have a TrueNAS CORE 12 installation with democratic-csi configured to use ssh commands with the `freenas-nfs` driver.

I am considering running a CORE -> SCALE migration for various reasons and there are a couple of questions I need to understand before I start.

1. In the short term, will my existing democratic-csi deployment continue working via ssh (I may need to tweak the locations of the binaries in the config)?
2. When I later migrate to the `freenas-api-nfs` driver, is it possible to upgrade my democratic-csi deployment to work over the API instead of ssh, maintaining my existing storage class and PVs?

Thanks. If I go ahead with the migration, I'll write something for your docs.

**Comment by travisghansen** [comment]
While I don’t ‘support’ this, nothing meaningful should prevent either from working. You may run into something quirky but I don’t think it would prevent proper function quickly (ie: maybe your ssh key won’t work because of the change of defaults, or you need to tweak something simple in the configuration from a string type to a numeric type). The data as stored as zfs props should be compatible between the 2 and I don’t foresee anything in the future that would alter that either.

**Comment by djjudas21** [comment]
Thanks, good to know. When I've got a bit of time I'll attempt this migration and document the process.

**Comment by travisghansen** [comment]
You would want a copy of the truenas db/config for sure as the shares stored in the db would need to retain the existing IDs etc or bad things will happen. Otherwise from a pure data standpoint I think zfs send/receive will be fine, I would just confirm that the custom props set on the zvols/datasets are present.

**Comment by djjudas21** [comment]
I ran through the migration from CORE 13 to SCALE 22.12.0 by using the web UI to switch upgrade path. The upgrade completed successfully. I hit a minor snag when it booted up into the new OS for the first time - the NFS server daemon wouldn't start because of an error where it thought there were no NFS shares defined (there were).

Turns out this is a known issue with 22.02.0 (and apparently 22.12 too) where if you have NFS shares with `mapall` or `maproot` set. On BSD, `mapall` would typically be set to `nobody:nobody` but on Linux the `nobody` group does not exist, and should be changed to `nobody:nogroup`.

> Unable to mount an NFS export after migrating from
> CORE > SCALE or updating to 22.02.0.
> The /etc/exports file is no longer generated when the NFS configuration contains mapall or maproot entries for
> unknown users or groups. This can impact users who previously had a mapping group set to wheel, which does
> not exist in SCALE. If you are unable to mount an NFS export, review your NFS share configuration and change any
> wheel entries to something specific for your environment or root.

In the short term, you can work around this by SSHing onto TrueNAS and doing `touch /etc/exports` to allow nfs-server to start up. Then you need to fix the `mapall`/`maproot` settings for every defined share before you reboot again.

I did not need to make any adjustments to my democratic-csi deployment to make it work with TrueNAS SCALE, but I will be making the adjustment so it uses the HTTP API instead of SSH shell commands.

Hope these notes are useful to someone!
