### ISSUE TITLE
How do I specify the name of the underlying ZVOL?

### ISSUE THREAD

**Issue by UntouchedWagons** [democratic-csi/democratic-csi#300]
My `freenas-api-iscsi.yaml`

    csiDriver:
      # should be globally unique for a given cluster
      name: "org.democratic-csi.iscsi"

    # add note here about volume expansion requirements
    storageClasses:
    - name: freenas-iscsi-csi
      defaultClass: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        # for block-based storage can be ext3, ext4, xfs
        # for nfs should be nfs
        fsType: ext4
          
        # if true, volumes created from other snapshots will be
        # zfs send/received instead of zfs cloned
        # detachedVolumesFromSnapshots: "false"
        
        # if true, volumes created from other volumes will be
        # zfs send/received instead of zfs cloned
        # detachedVolumesFromVolumes: "false"

      mountOptions: []
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
    #      # any arbitrary iscsiadm entries can be add by creating keys starting with node-db.<entry.name>
    #      # if doing CHAP
    #      node-db.node.session.auth.authmethod: CHAP
    #      node-db.node.session.auth.username: foo
    #      node-db.node.session.auth.password: bar
    #
    #      # if doing mutual CHAP
    #      node-db.node.session.auth.username_in: baz
    #      node-db.node.session.auth.password_in: bar
        node-publish-secret:
        controller-expand-secret:

    # if your cluster supports snapshots you may enable below
    volumeSnapshotClasses: []
    #- name: freenas-iscsi-csi
    #  parameters:
    #  # if true, snapshots will be created with zfs send/receive
    #  # detachedSnapshots: "false"
    #  secrets:
    #    snapshotter-secret:

    driver:
      config:
        driver: freenas-api-iscsi
        instance_id:
        httpConnection:
          protocol: https
          host: 192.168.20.5
          port: 443
          apiKey: 3-eZmWsZp1ipVHJCtGygrQU6E0vanLIqrrb6IQ2kn9unsK58vJtoIoX3rIssfnf1rG
          allowInsecure: true
          apiVersion: 2

        zfs:
          datasetParentName: tank/K8S/Vols
          detachedSnapshotsDatasetParentName: tank/K8S/Snaps
          datasetProperties:
          "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          zvolCompression: ""
          zvolDedup: ""
          zvolEnableReservation: false
          zvolBlocksize: "16K"

        iscsi:
          targetPortal: "192.168.20.5:3260"
          targetPortals: []
          interface:
          namePrefix: ""
          nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          nameSuffix: ""
          targetGroups:
            - targetGroupPortalGroup: 2
              targetGroupInitiatorGroup: 1
              targetGroupAuthType: None
              targetGroupAuthGroup:
          extentCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          # 512, 1024, 2048, or 4096,
          extentBlocksize: 4096
          # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
          extentRpm: "7200"
          # 0-100 (0 == ignore)
          extentAvailThreshold: 0

When I create a PVC the created iSCSI target is default-pvc-test or whatever the $namespace-$PVC_name is, but the underlying ZVOL that's created is csi-$UUID. How do I specify the name of the ZVOL that's created? I tried using nameTemplate as I did with the iscsi target but that didn't work. I'd like the zvol and iscsi targets to be reused if the PVC gets recreated.

**Comment by travisghansen** [comment]
You can read through this: https://github.com/democratic-csi/democratic-csi/issues/289

Short is I don't support and likely never will..but pretty soon you'll like have an advanced option to do that kind of setup but it's not recommended. Even using a name for the template is not recommended as well as you can relatively easily hit the limits and have issues.

**Comment by muhlba91** [comment]
@travisghansen is there any "update"?

i have the following baseline:
- have an external storage system exposing zfs and iscsi/smb
- use this CSI driver to create PVC/PV for persistent storage hooking it up with the provided external storage system using ZFS
  - this will create a ZVOL and iscsi target or smb share

now, i face a kubernetes disaster but due to automation i bascially can recreate the entire cluster in a few minutes and deploy all applications automatically (flux or argo, for example).

in such a case, the data still exists in the original ZVOLs and iscsi targets on the external storage system. in the easiest case i'd like to be able to kinda reuse the same targets and ZVOLs and have the data "restored" in this way.
hence, being able to "reuse/set" the ZVOL and target name (template) is pretty useful. i do understand implications regarding limits and such but, in the end, it's also up to me if using such a template to ensure limits are taken care of.

btw. yes, i can hook in velero or similar but that would make restoring the cluster an inherently manual task since i need to restore PV/PVCs before any automation like flux or argo kicks in and creates those automatically.

**Comment by travisghansen** [comment]
@muhlba91 all the details are in the previously linked ticket, as mentioned it's unsupported but you are welcome to give it a go!
