### ISSUE TITLE
clarification on local-hostpath and zfs-local-dataset snapshots

### ISSUE THREAD

**Issue by abasitt** [democratic-csi/democratic-csi#328]
Sorry this is not an issue and may be a trivial question but i am struggling to find an answers.

I want to use csi driver for local-path but with snapshot support. I am currently using k3s local-path provisioner which doesn't support snapshots for pvc.

Can someone clarify below if democratic-csi local-hostpath snapshot works with any file system or the file system has to be zfs ?. Currently I have single disk VMs with root filesystem as ext4. If ext4 doesn't work, i am thinking of provisioning VMs with two disks, root with ext4 and additional disk which is zfs formatted for local-hostpath and this bring me to another question.

If I have a zfs volume, which driver is a good idea to use ? local-host path or zfs-local-dataset.

Thank you.

**Comment by travisghansen** [comment]
Welcome! `local-hostpath` does have snapshot support that works with any volume but I would not call it an enterprise solution. It simply invokes `rsync` and copies the data to the same fs (unless you create a new mount at `{controllerBasePath}/s`).

If you have zfs available then I would highly recommend using that over `local-hostpath`. It includes quota support and does snapshots using `zfs snapshot` functionality instead of `rsync`.

**Comment by abasitt** [comment]
Thank you so much @travisghansen, this is very helpful to know.
