### ISSUE TITLE
How to customize iscsi/nfs deployments 

### ISSUE THREAD

**Issue by kingnarmer** [democratic-csi/democratic-csi#331]
I am looking for a way to customize democratic csi install . Few things I have in mind.

* How to specify Resource Requests and Limits ?
* Can I limit capabilities in securityContext to what iscsi/nfs deployments need ?
* Can I run on csi pods in non-root ?
* Can I disable  PrivilegeEscalation ?

Thanks for your effort

**Comment by travisghansen** [comment]
Welcome! In general csi drivers (not just this project) require fully elevated privileges due to the nature of what they do (mounting, formatting, etc, etc).

If your search for `resources` or `securityContext` here you will find the available options: https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml

Updates to the chart are welcome should you find something lacking that needs to be added.
