### ISSUE TITLE
freenas-api-iscsi - TrueNas Scale Dragonfish-24.04.2 Initiator Group Deleted when last pvc is removed

### ISSUE THREAD

**Issue by hollanbm** [democratic-csi/democratic-csi#412]
Using the provided `freenas-api-iscsi` example, I'm able to setup and deploy democratic-csi

However, when the last PVC created by democratic-csi, is deleted. The corresponding initiator group in TNS is also deleted. Which then prevents me from creating additional volumes.

I can manually go in, recreate the initiator group, and update the driver config, and it will resume operation.

I can provide logs if need be, but I'm not sure what would be helpful, this is pretty easy to recreate

**Comment by travisghansen** [comment]
Welcome! I don't think code in the repo manages the initiator groups at all, so I am guessing it's some logic in the TN middleware :(

**Comment by hollanbm** [comment]
> Welcome! I don't think code in the repo manages the initiator groups at all, so I am guessing it's some logic in the TN middleware :(

That’s what I was afraid of.

If you can point me at the files, I can write a sentence or something to update the documentation?

**Comment by travisghansen** [comment]
I think it’s best to file a bug with TN. IMO it shouldn’t do that :(

**Comment by andrea-mattioli** [comment]
The problem lies in the TrueNAS code. If you delete a target associated with an initiator group, by default, it also removes the initiator group. This does not happen if you have multiple targets associated with the initiator group. I recommend creating a small PVC in a dummy project that you will never touch again. This allows you to maintain the integrity of a static initiator group.

P.S. Remember to update the YAML file by inserting the correct ID of the last initiator group. Unfortunately, when it deletes and recreates it, TN adds +1 to the key in the database, and then the driver no longer works:
```
targetGroups:
    # Get the correct ID from the "portal" section in the UI
    # https://github.com/democratic-csi/democratic-csi/issues/302
    # NOTE: the ID in the UI does NOT always match the ID in the DB, you must use the DB value
    - targetGroupPortalGroup: 1
      # Get the correct ID from the "initiators" section in the UI
      targetGroupInitiatorGroup: 1 @@ THIS ONE @@
      # None, CHAP, or CHAP Mutual
      targetGroupAuthType: None
      # Get the correct ID from the "Authorized Access" section of the UI
      # Only required if using Chap
      targetGroupAuthGroup:
```

**Comment by travisghansen** [comment]
https://ixsystems.atlassian.net/browse/NAS-135243
