### ISSUE TITLE
Behaviour when draining node

### ISSUE THREAD

**Issue by djjudas21** [democratic-csi/democratic-csi#43]
So this is really a request for information...

I have now got TrueNAS working great with my single-node microk8s "cluster", and I have migrated all my workloads to use either iSCSI or NFS volumes via democratic, and nothing is using microk8s hostpath storageclass any more. I then added 3 additional nodes to the cluster to make it truly HA, and I confirmed that pods can be successfully scheduled on other nodes and can access their volumes in TrueNAS successfully.

So I now wish to drain my original node for maintenance and it gets stuck with the democratic controllers which are still scheduled on the original node:

```
[jonathan@zeus ~]$ kubectl drain zeus.jg.lan --ignore-daemonsets
node/zeus.jg.lan already cordoned
error: unable to drain node "zeus.jg.lan", aborting command...

There are pending nodes to be drained:
 zeus.jg.lan
error: cannot delete Pods with local storage (use --delete-local-data to override): democratic-csi/zfs-iscsi-democratic-csi-controller-5888fb7c46-xdmx6, democratic-csi/zfs-nfs-democratic-csi-controller-6757778446-87xps
```

Are the controllers really using local storage, or is this just a complication of mounting iSCSI on the local filesystem? Is it safe for me to specify `--delete-local-data` without losing my data in TrueNAS or my current state of PVCs etc? There are no PVCs or PVs in use by the democratic controllers so I assume it means ephemeral storage?

**Comment by djjudas21** [comment]
I assume the problematic storage is the `socket-dir` mount, as the other two are secrets

```
kubectl describe pod zfs-iscsi-democratic-csi-controller-5888fb7c46-xdmx6
...
Volumes:
  socket-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  zfs-iscsi-democratic-csi-driver-config
    Optional:    false
  zfs-iscsi-democratic-csi-controller-sa-token-bkwd5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  zfs-iscsi-democratic-csi-controller-sa-token-bkwd5
    Optional:    false
```

**Comment by djjudas21** [comment]
Yes, according to the [kubernetes docs](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#drain):

Name | Shorthand | Default | Usage
-- | -- | -- | --
`delete-local-data` |   | `false` | Continue even if there are pods using emptyDir (local data that will be deleted when the node is drained).

So my question is, is the data in the emptyDir `socket-dir` just the socket for the controller daemon, or does it have any state? I'm just being super-cautious of my data. Thanks

**Comment by travisghansen** [comment]
No state is stored and it’s perfectly safe to drain with that option (not only in the case of democratic-csi but generally). It’s highly unlikely that an app would put anything of meaning in an emptyDir anyhow :)

**Comment by djjudas21** [comment]
Thanks for confirming. The name `socket-dir` filled me with hope, but seeing that it was mounted into the pod at `/csi-data` made me worry there might be something else in there!

**Comment by travisghansen** [comment]
I was very careful/adamant about not requiring persistent data to run the app...I didn’t want chicken/egg scenarios where you need storage to provide storage :)

That is how/why I came up with the crazy idea of using zfs properties as my datastore on the backend.

**Comment by djjudas21** [comment]
Well thanks for your efforts. I just drained the node and all pods were successfully rescheduled to other nodes and all mounted their storage successfully, so I can fix the original node that had problems. I've had a great experience with democratic-csi so I plan to write this up in a blog post at some point :+1:

**Comment by travisghansen** [comment]
Share the post so I can read it!

**Comment by djjudas21** [comment]
Here you go! https://jonathangazeley.com/2021/01/05/using-truenas-to-provide-persistent-storage-for-kubernetes/

Please feel free to suggest corrections if I haven't explained something properly, and also feel free to link to this in your README, or even plagiarise some of the text!

Thanks for your help getting this working in my environment :grinning:

**Comment by travisghansen** [comment]
Thanks! I’ll check it out!

**Comment by travisghansen** [comment]
Very cool! I'd be happy to add a guides section to the readme and place the link there.

Here are a few notes I have:

- This is technically incorrect verbiage here, **zvols** are created **from** zfs **pools**, **pools** are created from **vdevs** which are 1+ **block devices**:
```
A complete guide to TrueNAS is outside the scope of this article, but basically you’ll want to create a zvol out of your disks and then create a single pool on the zvol.
```
- I would simply say a working pool is required to use the driver
- `so under hdd I created a sub pool k8s` - these are actually called **datasets**
- personal preference, but nfs4 is a hot mess IMO so I don't use that with k8s, and objectively it's likely a worse option than v3 due to how the permission model works (it's designed to integrate with the likes of AD, and containers don't really mesh with that model at all). However, I'm not an nfsv4 expert and diversity of configuration is good, especially if it works :)
- `An Initiator Group allows you to define which Initiators can connect to your Portal` - this is technically incorrect, initiator groups are used to define which **targets** the clients/initiators can connect to
- The easiest way to think about the 3, targets, extents, and 'associated targets' is like this:
  - target - this is analogous to an hba or hdd 'card'
  - extent - these are hdds
  - 'associated targets' - are cables between the hdd(s) and the hba(s)
  - initiators login to **targets** or hbas and this creates a 'session'
  - session is a cable between the client and the hba (in some ways analogous to a pcie slot for example where the hba is plugged in...except that an hba can only be plugged into a single physical slot whereas a target can be connected to from many initiators)
- the inclusion of instructions for selinux is aweomse! thanks!
- `I found this a little confusing but these two values should be direct children of whatever your nfs pool is.` - this a good rule of thumb for simplistic use-cases, however, the **detachedSnapshotsDatasetParentName** can be *any* **pool**/**dataset** available on the node/server. At some point I actually intend to make it possible to point to a *remote* host even. The idea here being when using snapshots for *backup* purposes that you get the data on separate underlying physical disks. This was a very specific design decision as I had started to make those values implied and have a simple single configuration option but then I backed it out to support the separate pool/node scenarios.
- iscsi prep is missing the ubuntu/debian instructions
- in the iscsi section you referenced the nfs pool..`I found this a little confusing but these two values should be direct children of whatever your nfs pool is.`
- toward the end I would suggest having users also confirm the shares are present (both nfs and iscsi shares) in addition to confirming the zfs datasets/zvols exist
- after deleting the pvcs I would also suggest doing the same thing (confirming zfs datasets/zvols are gone along with various shares)

This is really great to have more complete how-tos for folks to reference! I have 1 more thing I want to look into and then I'll be snapping a 1.0 release so this will be great to coincide with that!

**Comment by djjudas21** [comment]
Wow, you obviously read this in great detail. I'll fix the mistakes in my post and hopefully it will be a useful reference.

**Comment by travisghansen** [comment]
Yeah, shout out after you've updated and I'll do another pass and add it to the README!

**Comment by djjudas21** [comment]
I've just published an update... what do you think?

**Comment by travisghansen** [comment]
Great! I'll add it to the README when I get a moment.

**Comment by travisghansen** [comment]
Added to the `next` branch. Will merge with that.

**Comment by travisghansen** [comment]
Would it be possible to update your blog post and add a note about ensuring bash/sh as the shell instead of csh?

**Comment by djjudas21** [comment]
Sure can. What's the detail I need to provide? It's not one I've run into before

**Comment by travisghansen** [comment]
The default shell these days for root is csh and it produces a false error about quoting problems. So just a note ensuring that the user used for ssh connection has bash/sh set as the shell would be great. I have it in the readme but it’s easy to miss.

**Comment by djjudas21** [comment]
Interesting. I never explicitly set any shell but never had any problems. I just checked and it is using zsh as the default. I'll mention this in the blog.

**Comment by djjudas21** [comment]
Anyway, I've updated my blog post with a note about SSH config and shells.

**Comment by travisghansen** [comment]
Yeah I think the default shell has changed over time so if you’ve upgraded your install you likely don’t have csh. zsh should work fine (or at least my testing indicated so).

Thanks for updating!
